import { Renderer, marked } from 'marked'

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

// Raw HTML embedded in the markdown source (blocks or inline tags) is escaped
// instead of passed through, since the rendered output is injected via
// dangerouslySetInnerHTML below.
const renderer = new Renderer()
renderer.html = ({ text }) => escapeHtml(text)

interface MarkdownReportProps {
  content: string
}

export function MarkdownReport({ content }: MarkdownReportProps) {
  const html = marked.parse(content, { async: false, gfm: true, renderer })

  return (
    <div
      className="markdown-report rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-6"
      // biome-ignore lint/security/noDangerouslySetInnerHtml: content is markdown generated by our own report pipeline; raw HTML tokens are escaped by the renderer override above
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
